--1 STG_CUSTOMERS DATA CLEANING

--Total Rows
SELECT COUNT(*) FROM STG_CUSTOMERS;--50000 ROWS
--CHECK NULLS
SELECT SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_ID_NULLS,
	   SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS AGE_NULLS,
	   SUM(CASE WHEN GENDER IS NULL THEN 1 ELSE 0 END) AS GENDER_NULLS,
	   SUM(CASE WHEN LOYALTY_MEMBER IS NULL THEN 1 ELSE 0 END) AS LOYALTY_MEMBER_NULLS,
	   SUM(CASE WHEN JOIN_DATE IS NULL THEN 1 ELSE 0 END) AS JOIN_DATE_NULLS

	   FROM STG_CUSTOMERS;--NO NULLS FOUND

---CHECK DUPLICATES
SELECT CUSTOMER_ID, COUNT(*) AS DUPLICATE_COUNT
FROM STG_CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;--NO DUPLICATES FOUND
--Check Invalid Ages
SELECT *
FROM STG_CUSTOMERS
WHERE age < 0
   OR age > 100;---NO INVALID AGES FOUND
--Check Gender Values
SELECT DISTINCT gender
FROM STG_CUSTOMERS;--MALE/FEMALE
--Check Loyalty Member Values
SELECT DISTINCT loyalty_member
FROM STG_CUSTOMERS;--0/1
--DATA TYPE CHECKS
EXEC sp_help 'STG_CUSTOMERS';

---- Invalid date
SELECT * FROM STG_CUSTOMERS
WHERE TRY_CONVERT(DATE, join_date) IS NULL
  AND join_date IS NOT NULL;--CORRECT

--FINAL CUSTOMERS RABLE CREATE
CREATE TABLE CUSTOMERS (
    customer_id VARCHAR(50) PRIMARY KEY,
    age INT,
    gender VARCHAR(20),
    loyalty_member BIT,--BIT DATA TYPE FOR BINARY VALUES 0/1
    join_date DATE
);

INSERT INTO CUSTOMERS
SELECT
    customer_id,
    age,
    gender,
    loyalty_member,
    CAST(join_date AS DATE)
FROM STG_CUSTOMERS;

  --2 STG_PRODUCTS DATA CLEANING
  --DATA RANGE 
  SELECT * FROM STG_PRODUCTS;
  SELECT COUNT(*) FROM STG_PRODUCTS;--200 ROWS
  --NULL CHECKS
  SELECT SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS PRODUCT_ID_NULLS,
	   SUM(CASE WHEN PRODUCT_NAME IS NULL THEN 1 ELSE 0 END) AS PRODUCT_NAME_NULLS,
	   SUM(CASE WHEN CATEGORY IS NULL THEN 1 ELSE 0 END) AS CATEGORY_NULLS,
	   SUM(CASE WHEN COCOA_PERCENT IS NULL THEN 1 ELSE 0 END) AS COCOA_PERCENT_NULLS,
	   SUM(CASE WHEN WEIGHT_G IS NULL THEN 1 ELSE 0 END) AS WEIGHT_G_NULLS
	   FROM STG_PRODUCTS;--NO NULLS FOUND
--DUPLICATE CHECKS
SELECT PRODUCT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM STG_PRODUCTS
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 1;--NO DUPLICATES FOUND
---CHECK COLUMN PRODUCT NAME
SELECT DISTINCT product_name FROM STG_PRODUCTS;--ALL PRODUCT NAMES ARE VALID
--COCOA PERCENTEAGE VALIDATION
SELECT * FROM STG_PRODUCTS
WHERE cocoa_percent < 0 OR cocoa_percent > 100;--NO INVALID COCOA PERCENTAGE FOUND
---Weight Validation
SELECT *
FROM STG_PRODUCTS
WHERE weight_g <= 0;--CORRECT
--CHECK CATEGORY
SELECT DISTINCT category FROM STG_PRODUCTS;--ALL CATEGORIES ARE VALID
--Final Validation
SELECT
    COUNT(*) AS TotalRows,
    COUNT(product_id) AS ProductID_NotNull,
    COUNT(product_name) AS ProductName_NotNull
FROM STG_PRODUCTS;-- -ALL VALIDATIONS PASSED

--FAINAL PRODUCTS TABLE CREATE
CREATE TABLE PRODUCTS (
    product_id VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(255),
    brand VARCHAR(100),
    category VARCHAR(100),
    cocoa_percent INT,
    weight_g INT
);

--LOAD DATA INTO PRODUCTS TABLE
INSERT INTO PRODUCTS
SELECT DISTINCT *
FROM STG_PRODUCTS;

SELECT * FROM PRODUCTS;

--3  STG_STORES DATA CLEANING
SELECT COUNT(*) FROM STG_STORES;--100 ROWS
--CHECK NULLS
SELECT 
       SUM(CASE WHEN STORE_ID IS NULL THEN 1 ELSE 0 END) AS STORE_ID_NULLS,
       SUM(CASE WHEN STORE_NAME IS NULL THEN 1 ELSE 0 END) AS STORE_NAME_NULLS,
       SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END) AS CITY_NULLS,
       SUM(CASE WHEN COUNTRY IS NULL THEN 1 ELSE 0 END) AS COUNTRY_NULLS,
       SUM(CASE WHEN STORE_TYPE IS NULL THEN 1 ELSE 0 END) AS STORE_TYPE_NULLS
       FROM STG_STORES;--NO NULLS FOUND

       --CHECK DUPLICATES
       SELECT STORE_ID, COUNT(*) AS DUPLICATE_COUNT
       FROM STG_STORES
       GROUP BY STORE_ID
       HAVING COUNT(*) > 1;--NO DUPLICATES FOUND

       ---CHECK STORE TYPE
       SELECT DISTINCT store_type
       FROM STG_STORES;--ALL STORE TYPES ARE VALID
       --CHESK STORE NAME 
       SELECT DISTINCT store_name FROM STG_STORES;--ALL STORE NAMES ARE VALID
---EXTRA SPACES CHECK
  SELECT * FROM STG_STORES WHERE
    store_id <> TRIM(store_id)
    OR store_name <> TRIM(store_name)
    OR city <> TRIM(city)
    OR country <> TRIM(country)
    OR store_type <> TRIM(store_type);---NO EXTRA SPACES FOUND

    --Create Final Table STORES
CREATE TABLE STORES (
    store_id VARCHAR(50) PRIMARY KEY,
    store_name VARCHAR(255),
    city VARCHAR(100),
    country VARCHAR(100),
    store_type VARCHAR(100)
);

--LOAD DATA INTO STORES TABLE
INSERT INTO STORES
SELECT DISTINCT *
FROM STG_STORES;

--4 STG_SALES CLEANING
--CHECK TOTAL ROWS = 1000000
SELECT COUNT(*) FROM STG_SALES;
--CHECK NULLS
SELECT SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS ORDER_ID_NULLS,
       SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS PRODUCT_ID_NULLS,
       SUM(CASE WHEN STORE_ID IS NULL THEN 1 ELSE 0 END) AS STORE_ID_NULLS,
       SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_ID_NULLS,
       SUM(CASE WHEN QUANTITY IS NULL THEN 1 ELSE 0 END) AS QUANTITY_NULLS,
       SUM(CASE WHEN ORDER_DATE IS NULL THEN 1 ELSE 0 END) AS ORDER_DATE_NULLS,
       SUM(CASE WHEN COST IS NULL THEN 1 ELSE 0 END) AS COST_NULLS,
       SUM(CASE WHEN UNIT_PRICE IS NULL THEN 1 ELSE 0 END) AS UNIT_PRICE_NULLS,
       SUM(CASE WHEN DISCOUNT IS NULL THEN 1 ELSE 0 END) AS DISCOUNT_NULLS,
       SUM(CASE WHEN REVENUE IS NULL THEN 1 ELSE 0 END) AS REVENUE_NULLS,
       SUM(CASE WHEN PROFIT IS NULL THEN 1 ELSE 0 END) AS PROFIT_NULLS
       FROM STG_SALES;---NO NULLS FOUND

       --DUPLICATE CHECK
       SELECT ORDER_ID,PRODUCT_ID,CUSTOMER_ID,STORE_ID, COUNT(*) AS DPC FROM STG_SALES
       GROUP BY ORDER_ID, PRODUCT_ID, CUSTOMER_ID, STORE_ID
       HAVING COUNT(*) > 1;---NO DUPLICATE ROWS FOUND

 --CHECK SPACE       
SELECT * FROM STG_SALES WHERE order_id <> TRIM(order_id)
                              OR product_id <> TRIM(product_id)
                              OR store_id <> TRIM(store_id)
                              OR customer_id <> TRIM(customer_id)
                              OR order_date <> TRIM(order_date);--NO SPCES
--Check Invalid Order Dates
SELECT *
FROM STG_SALES
WHERE TRY_CONVERT(DATE, order_date) IS NULL
                 AND order_date IS NOT NULL;---NO INVALID ORDER DATES
---CHECK THE NEGATIVE VALUE AND ZERO
SELECT *
FROM STG_SALES
WHERE quantity <= 0
      OR unit_price < 0
      OR revenue < 0
      OR discount < 0
      OR PROFIT < 0;  ---NO NEGATIVE VALUE FOUND
      
--Validate Profit Formula
SELECT *
FROM STG_SALES
WHERE ABS((revenue - cost) - profit) > 0.01;--CORRECT
--Customer FK Validation (Final Check)
SELECT *
FROM STG_SALES s
WHERE NOT EXISTS (
    SELECT 1
    FROM STG_CUSTOMERS c
    WHERE c.customer_id = s.customer_id
);--CORECT

--Product FK Validation (Final Check)
SELECT *
FROM STG_SALES s
WHERE NOT EXISTS (
    SELECT 1
    FROM STG_PRODUCTS p
    WHERE p.product_id = s.product_id
);

DELETE s
FROM STG_SALES s
LEFT JOIN STG_PRODUCTS p
    ON s.product_id = p.product_id
WHERE p.product_id IS NULL;
-- STG_SALES table has 202 distinct Product_IDs, while STG_PRODUCTS has 200.
-- 2 Product_IDs are missing in PRODUCT, resulting in 9,764 unmatched sales records.
--CHECK
SELECT DISTINCT s.product_id
FROM STG_SALES s
LEFT JOIN STG_PRODUCTS p
    ON s.product_id = p.product_id
WHERE p.product_id IS NULL;
--Store FK Validation
SELECT *
FROM STG_SALES s
WHERE NOT EXISTS (
    SELECT 1
    FROM STG_STORES st
    WHERE st.store_id = s.store_id
);--CORRECT

--Create Final SALES Table
CREATE TABLE SALES (
    order_id VARCHAR(50) PRIMARY KEY,
    order_date DATE NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    store_id VARCHAR(50) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    discount DECIMAL(10,2) NOT NULL,
    revenue DECIMAL(12,2) NOT NULL,
    cost DECIMAL(12,2) NOT NULL,
    profit DECIMAL(12,2) NOT NULL,

    CONSTRAINT FK_SALES_PRODUCTS
        FOREIGN KEY (product_id)
        REFERENCES PRODUCTS(product_id),

    CONSTRAINT FK_SALES_STORES
        FOREIGN KEY (store_id)
        REFERENCES STORES(store_id),

    CONSTRAINT FK_SALES_CUSTOMERS
        FOREIGN KEY (customer_id)
        REFERENCES CUSTOMERS(customer_id)
);

--LOAD DATA INTO SALES TABLE
INSERT INTO SALES 
SELECT DISTINCT order_id,
    CAST(order_date AS DATE),
    product_id,
    store_id,
    customer_id,
    quantity,
    unit_price,
    discount,
    revenue,
    cost,
    profit
FROM STG_SALES;

--VALIDATE FINAL TABLES
SELECT COUNT(*) AS Customer_Count FROM CUSTOMERS;--50000
SELECT COUNT(*) AS Product_Count FROM PRODUCTS;--200
SELECT COUNT(*) AS Store_Count FROM STORES;--100
SELECT COUNT(*) AS Sales_Count FROM SALES;--990236










